config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'sessions/new'
  root           'static_pages#home'
  get 'help', 	   to: 'static_pages#help'
  get 'about',     to: 'static_pages#about'
  get 'contact',   to: 'static_pages#contact'
  # get 'signup',    to: 'users#new'
  get 'login' ,    to: 'sessions#new'
  post 'login',    to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # get 'user/:id',      to: 'users#show'
  # get 'user/:id',   to: 'users#show', as: 'user'

  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true
  def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
  	BCrypt::Password.create(string, cost: cost)
  end

  def new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.update_attribute(:remember_digest, new_token)
  end

  def authenticated?(rememeber_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # layout 'custom'
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
      flash.now[:success] = "You are succesfully logged in"
  	else
  	  redirect_to login_path, flash: { danger: "Invalid email/password combination" }
    end
  end

  def destroy
    # user = User.find_by(id: params[:id])
    # session[:user_id] = nil
    log_out if logged_in?
    redirect_to root_path, flash: { success: "You have succesfully logged out" }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_users, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user
  
  def index
    @users = User.page params[:page]
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      redirect_back_or (@user), flash: { success: "welcome to the Sample App!" } 
  	else 
      redirect_to new_user_path, flash: { danger: @user.errors }
  	end
  end

  def edit

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, flash: {success: "attributes updated"}
    else
      redirect_to edit_user_path
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "You have successfully deleted User"
    redirect_to users_url
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_users
    unless logged_in?
      store_location
      redirect_to login_path, flash: { danger: "Please log in"}
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to (root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Ruby tutorial"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent[:remember_token] = user.remember_token		
		cookies.permanent.signed[:user_id] = user.id
	end



	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def current_user?(user)
		user == current_user
	end

	def logged_in?
		!current_user.nil?
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.url if request.get?
	end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# returns Gravatar image
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class = "footer">
	<div class="columns">
	<div class="column is-4">
	<div class="content has-text-centred">
		the <a href="https://google.com"> google </a>
	</br>
		the <a href="https://github.com/h4ppyr0gu3/"> official github site</a>
	</div>
</div>
	<div class="column is-2 ">
			<%= link_to "About", about_path, class: "foot_item"%>
		</div>
			<div class="column is-2">
			<%= link_to "Contact", contact_path, class: "foot_item"%>
		</div>
		<div class="column is-2 foot_item">
			<a href="https://github.com/h4ppyr0gu3/"> News </a>  
		</div>
</div>
</div>

</footer>

app/views/layouts/_header.html.erb
<nav class="navbar container" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu has-text-black">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to "SAMPLE APP", root_path, class: "is-size-2 is-button is-black is-bold" %>
      </div>
    </div>
    <div class="navbar-end">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <%= link_to "Help", help_path, class: "navbar-item" %>
      <% if logged_in? %>
        <%= link_to "Users", users_path, class: "navbar-item" %>
        <div class="navbar-item has-dropdown" id="dropdown_button">
          <a class="navbar-link">
            Account
          </a>
          <div class="navbar-dropdown">

            <%= link_to "Profile", user_path(current_user), class: "navbar-item" %>
            <%= link_to "settings", edit_user_path(current_user), class: "navbar-item" %>
            <hr class="navbar-divider">

            <%= button_to "Log out", logout_path, :method => :delete, class: "navbar-item" %>
          </div>
      <% else %>
        <div class="buttons">
          <%= link_to "Log In", login_path, class: "navbar-item button is-primary" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <link rel="icon" type="image/png" href="https://en.wikipedia.org/wiki/Google_logo#/media/File:Google_2015_logo.svg"/> -->
  <title><%=full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- [if it IE 9]> -->
  <%= render 'layouts/shim' %>
</head>

<body>
    <%= csrf_meta_tags %>

  <%= render 'layouts/header' %>

  <div class = 'container'>
    <% if !flash.empty? %>
     <% flash.each do |message_type, message | %>
      <div class="notification is-<%= message_type %>" id="notification_box">
        <button class="delete" id="delete_btn"></button>
          <% if message.class == String %>
            <%= message %>

          <% else %>
            <% flash.each do |message_type, message| %>
              <% message.each do |key, values| %>
                <% values.each do |value| %>
                  <%= key %> <%= value %>
                  <br/>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          
        <% end %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    <div class="columns">
      <div class="column is-10 is-centre">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </div>

  <%= javascript_pack_tag 'navbar_toggle', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'delete_toggle', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>orwyfg</title>
</head>
<body>
	<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id = "error_explanation">
	<div class = "alert alert-danger">
		The form contains <%= pluralize(@user.errors.count, "error") %>
	</div>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<%end%>
	</ul>
</div>
<%end%>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="sampleapp/Bulma">
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        Hello World
      </h1>
      <p class="subtitle">
        My first website with <strong>Bulma</strong>!
      </p>
    </div>
  </section>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact us") %>

	<h1>Contact Us</h1>
	<p>
		The <a href="https://github.com/h4ppyr0gu3/"> google </a>
		This is the first href i have used
	</p>
	

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

  	<h1>StaticPages#help</h1>
  	<p>Find me in app/views/static_pages/help.html.erb</p>
    

app/views/static_pages/home.html.erb
<%= provide(:title, "Home") %>
<div class="container">
	<div class="centre">
		<h1>Welcome to the home page</h1>

		<h2>
			This is the homepage for the sample app
		</h2>
		<p>Find me in app/views/static_pages/home.html.erb</p>


		<%= link_to "sign up now!", new_user_path, class: "button button-is-primary" %>
		<%= link_to "Log in", login_path, class: "button button-is-primary" %>

	</div>
	<div class="" style="display: flex; justify-content: center; align-items: center;">
		<%= link_to image_tag("imagine.png", alt: "imagine image", class: "img-fluid", style: "max-width: 350px"), "#" %>
	</div>
</div>

app/views/users/_user-partial.slim
li
	= gravatar_for user, size: 50
	= link_to user.name, user

app/views/users/_user.slim
li
	= gravatar_for user, size: 50
	= link_to user.name, user
	- if current_user.admin? && !current_user?(user)
		.button
			= link_to "delete", user, method: :delete

app/views/users/_whateverthefuck.html.erb
<h1 class="text">
Some sqwueets
</h1> 

app/views/users/edit.slim
h1 Update your profile
.columns
	.column.is-6.is-offset-3
		= form_for(@user) do |f|
			= render 'shared/error_messages'

			.field
				= f.label :name, class: "label"
				= f.text_field :name, class: "form-control input", type: "text", placeholder: "name"

			.field
				= f.label :email, class: "label"
				= f.text_field :email, class: "form-control input", type: "text", placeholder: "email address"

			.field
				= f.label :password, class: "label"
				= f.password_field :password, class: "form-control input", type: "password", placeholder: "password"

			.field
				= f.label :password_confirmation, class: "label"
				= f.password_field :password_confirmation, class: "form-control input", type: "password", placeholder: "password"

			.field
				= f.submit "Save changes", class: "button is-primary"

			

app/views/users/index.slim
= provide(:title, "all users")
.container
	h1 All users

	ul.users

		= @users.count
		ul
			= render @users

		
	.card.pt-5
		.columns
			.column.is-6.is-offset-3
				= paginate @users

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class="columns">
<div class="column is-10 is-offset-1">
	<h1 class="text">Welcome to the signup page</h1>
	<p class="text_2">Sign up page for new customers</p>
	<%= form_for(@user) do |f| %>

	<%= render'users/whateverthefuck' %>

	<br>
	<div class = "columns">
		<div class = "column is-4">

			<%= f.label :name %>
			<%= f.text_field :name, class: "input", type: "text", placeholder: "Full Name" %>

		</div>
	</div>

	<div class = "columns">
		<div class = "column is-4">

			<%= f.label :email %>
			<%= f.email_field :email, class: "input", type: "text", placeholder: "Email address" %>
		</div>
	</div>
	<div class = "columns">
		<div class = "column is-4">
			<%= f.label :password %>
			<%= f.password_field :password, class: "input", type: "password", placeholder: "Password" %>
		</div>
	</div>

	<div class = "columns">
		<div class = "column is-4">
			<%= f.label :password_confirmation , "confirmation" %>
			<%= f.password_field :password_confirmation, class: "input", type: "password", placeholder: "Password" %>
		</div>
	</div>

	<%= f.submit "create my Account", class: "button is-primary" %>
	<%end%>
</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, "User") %>
<div class="column is-10 is offset-1">
<div class="columns">
	<div class="column is-4">
<%= @user.name %>, <%= @user.email %>
</div>
</div>
<div class = "columns">
	<aside class = "column is-4">
		<section class = "user_info">
			<h1>
				<%= gravatar_for @user %>
				<br>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>
</div>